# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The man who whispered to machines
tagline:          'a Ka0s Inc since 1986'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://new.ka0s.io
baseurl:          /

author:
  name:           'El man'
  url:            https://www.linkeding.com/in/alejandrosantacanacanton

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ka0score
