# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The man who whispered to machines
tagline:          'a Ka0s Inc since 1986'
description:      'Principalmente hablamos de automatizacion, ciberseguridad, desarrollo de software y temas relacionados con los diferentes modelos de BIL (Brother in Law).'
url:              http://news.ka0s.io
baseurl:          /

author:
  name:           'El man'
  url:            https://www.linkeding.com/in/alejandrosantacanacanton

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ka0score
